CREATE TABLE `clientPulse` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`clientId` int NOT NULL,
	`healthScore` int NOT NULL DEFAULT 100,
	`churnRisk` boolean NOT NULL DEFAULT false,
	`upsellReady` boolean NOT NULL DEFAULT false,
	`goingSilent` boolean NOT NULL DEFAULT false,
	`daysSinceLastContact` int DEFAULT 0,
	`daysSinceLastBooking` int DEFAULT 0,
	`daysSinceLastInvoice` int DEFAULT 0,
	`totalInvoicesPaid` int DEFAULT 0,
	`totalBookings` int DEFAULT 0,
	`followUpResponseRate` decimal(5,2) DEFAULT '0',
	`revenueLastThirtyDays` decimal(10,2) DEFAULT '0',
	`revenueLastNinetyDays` decimal(10,2) DEFAULT '0',
	`aiInsight` text,
	`aiAction` text,
	`aiActionType` varchar(32),
	`lastComputedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `clientPulse_id` PRIMARY KEY(`id`)
);
