CREATE TABLE `platformSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`siteName` varchar(255) NOT NULL DEFAULT 'TrueAxis HQ',
	`siteTagline` varchar(512) DEFAULT 'The AI-powered business platform for freelancers & coaches',
	`supportEmail` varchar(320) DEFAULT 'support@trueaxishq.com',
	`supportPhone` varchar(32),
	`announcementEnabled` boolean NOT NULL DEFAULT false,
	`announcementText` varchar(512),
	`announcementColor` varchar(32) DEFAULT 'teal',
	`socialTwitter` varchar(255),
	`socialLinkedin` varchar(255),
	`socialInstagram` varchar(255),
	`socialYoutube` varchar(255),
	`featureClientPulse` boolean NOT NULL DEFAULT true,
	`featureBookingPage` boolean NOT NULL DEFAULT true,
	`featureInvoicing` boolean NOT NULL DEFAULT true,
	`featureFollowUps` boolean NOT NULL DEFAULT true,
	`featureAnalytics` boolean NOT NULL DEFAULT true,
	`featureAIAssistant` boolean NOT NULL DEFAULT true,
	`maintenanceMode` boolean NOT NULL DEFAULT false,
	`maintenanceMessage` varchar(512),
	`freeTrialDays` int NOT NULL DEFAULT 14,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `platformSettings_id` PRIMARY KEY(`id`)
);
