import { useState, useEffect } from "react";
import { useLocation } from "wouter";
import { ArrowLeft, Zap, Search, ChevronDown, ChevronRight, Mail, MessageCircle, BookOpen, Zap as ZapIcon } from "lucide-react";

const categories = [
  {
    icon: ZapIcon,
    title: "Getting Started",
    articles: [
      {
        q: "How do I set up my TrueAxis HQ account?",
        a: "After signing in, you'll be guided through a quick onboarding flow. Enter your name, email, and business type. Then set up your booking page username in Settings → Booking Page. Your dashboard will be ready immediately with sample data to explore.",
      },
      {
        q: "How do I add my first client?",
        a: "Go to your Dashboard and click the 'Clients' tab. Click 'Add Client' in the top right, fill in their name, email, phone, and service type, then click Save. Your client will appear in the list immediately and their data will be available across all panels.",
      },
      {
        q: "How do I set up my public booking page?",
        a: "Go to Dashboard → Settings → Booking Page. Choose a username (e.g., yourname), add a bio, and list the services you offer. Your booking page will be live at trueaxishq.com/book/yourname. Share this link with clients so they can self-book without back-and-forth emails.",
      },
      {
        q: "What is included in the free trial?",
        a: "Your 14-day free trial includes full access to all Pro plan features: unlimited clients, invoicing, scheduling, AI follow-ups, analytics, and your public booking page. No credit card is required. After 14 days, you can choose a plan or your account will revert to the free tier.",
      },
    ],
  },
  {
    icon: Mail,
    title: "Invoicing",
    articles: [
      {
        q: "How do I create an invoice?",
        a: "In your Dashboard, click the 'Invoices' tab, then 'New Invoice'. Select a client, enter the service description, amount, and due date. You can add line items for detailed breakdowns. Click 'Create Invoice' to save it. The invoice will appear in your list with 'Draft' status.",
      },
      {
        q: "How do I mark an invoice as paid?",
        a: "Open the Invoices tab, find the invoice, and click the checkmark icon or open the invoice and click 'Mark as Paid'. The invoice status will update to 'Paid' and the revenue will be reflected in your Analytics dashboard immediately.",
      },
      {
        q: "Can I print or export invoices as PDF?",
        a: "Yes. Open any invoice and click the 'Print / Export PDF' button. This opens a print-optimized view of the invoice that you can save as a PDF using your browser's print dialog (File → Print → Save as PDF). The PDF includes your business name, client details, line items, and payment instructions.",
      },
      {
        q: "How do overdue invoices work?",
        a: "Any invoice with a due date in the past that has not been marked as paid will automatically display an 'Overdue' badge. The outstanding amount is tracked separately in your Analytics overview so you always know what you're owed.",
      },
    ],
  },
  {
    icon: BookOpen,
    title: "Scheduling & Bookings",
    articles: [
      {
        q: "How does the scheduling system work?",
        a: "The Scheduling tab in your Dashboard shows all your upcoming and past bookings. You can manually add bookings for clients, or clients can self-book via your public booking page. Each booking includes the client name, service, date/time, duration, and notes.",
      },
      {
        q: "How do clients book time with me?",
        a: "Share your booking page link (trueaxishq.com/book/yourname) with clients. They can select a service, choose a date and time, enter their name and email, and submit the booking. You'll receive a notification and the booking will appear in your Scheduling tab automatically.",
      },
      {
        q: "Can I block off time when I'm unavailable?",
        a: "Yes. In Dashboard → Settings → Booking Page, you can configure your availability by day of week and time range. Clients will only be able to book during your available hours. You can also manually mark specific dates as unavailable.",
      },
    ],
  },
  {
    icon: MessageCircle,
    title: "AI Follow-Ups",
    articles: [
      {
        q: "What are AI Follow-Ups?",
        a: "AI Follow-Ups are personalized email drafts generated by TrueAxis HQ's built-in language model. For each client, the AI writes a warm, professional follow-up email based on the client's name, service type, last session date, and any notes you've added. You review the draft and send it with one click.",
      },
      {
        q: "How do I generate a follow-up email?",
        a: "Go to Dashboard → Follow-Ups. You'll see all your clients listed with their last contact date. Click 'Generate' next to any client to have the AI write a personalized follow-up. You can edit the draft before sending. Click 'Send All' to generate and queue follow-ups for all clients at once.",
      },
      {
        q: "Can I customize the tone of follow-up emails?",
        a: "Yes. In the Follow-Ups panel, you can choose between Professional, Friendly, and Casual tones. You can also add custom notes about a client that the AI will incorporate into the email. All generated drafts are editable before sending.",
      },
    ],
  },
  {
    icon: Search,
    title: "Billing & Subscription",
    articles: [
      {
        q: "How do I upgrade or change my plan?",
        a: "Go to Dashboard → Billing. You'll see your current plan and options to upgrade. Click 'Upgrade Plan' to be taken to the Stripe checkout. After payment, your new plan features are activated immediately.",
      },
      {
        q: "How do I cancel my subscription?",
        a: "Go to Dashboard → Billing and click 'Manage Billing'. This opens the Stripe billing portal where you can cancel your subscription. Cancellation takes effect at the end of your current billing period — you'll retain access to paid features until then.",
      },
      {
        q: "What payment methods do you accept?",
        a: "We accept all major credit and debit cards (Visa, Mastercard, American Express, Discover) through Stripe. We also support Apple Pay and Google Pay in supported browsers.",
      },
      {
        q: "Do you offer refunds?",
        a: "We offer a 14-day free trial so you can evaluate the platform before paying. After a payment has been processed, we do not offer refunds for partial billing periods. If you believe you were charged in error, contact billing@trueaxishq.com and we'll investigate promptly.",
      },
    ],
  },
];

function ArticleAccordion({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border border-[#DDDBD7] rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen(o => !o)}
        className="w-full flex items-center justify-between gap-4 px-5 py-4 text-left hover:bg-white/5 transition-colors focus:outline-none focus:ring-2 focus:ring-[#D4922A] focus:ring-inset"
        aria-expanded={open}
      >
        <span className="text-sm font-medium text-[#1A1A1A]">{q}</span>
        <ChevronDown className={`w-4 h-4 text-[#6B6B6B] flex-shrink-0 transition-transform ${open ? "rotate-180" : ""}`} />
      </button>
      {open && (
        <div className="px-5 pb-5 text-sm text-[#3D3D3D] leading-relaxed border-t border-[#DDDBD7] pt-4">
          {a}
        </div>
      )}
    </div>
  );
}

export default function Help() {
  const [, navigate] = useLocation();
  const [search, setSearch] = useState("");
  const [activeCategory, setActiveCategory] = useState<string | null>(null);
  useEffect(() => { document.title = "Help Center — TrueAxis HQ"; }, []);

  const filtered = categories.map(cat => ({
    ...cat,
    articles: cat.articles.filter(
      a => !search || a.q.toLowerCase().includes(search.toLowerCase()) || a.a.toLowerCase().includes(search.toLowerCase())
    ),
  })).filter(cat => cat.articles.length > 0);

  return (
    <div className="min-h-screen bg-[#F2F0EC] text-[#1A1A1A]">
      <nav className="border-b border-[#DDDBD7] px-4 sm:px-6 py-4 flex items-center justify-between">
        <button onClick={() => navigate("/")} className="flex items-center gap-2 text-[#D4922A] hover:opacity-80 transition-opacity focus:outline-none focus:ring-2 focus:ring-[#D4922A] rounded px-2 py-1">
          <ArrowLeft className="w-4 h-4" />
          <span className="text-sm font-medium">Back to Home</span>
        </button>
        <div className="flex items-center">
          <img
            src="https://d2xsxph8kpxj0f.cloudfront.net/310519663405218930/gipzWtYeMsnYWyzsuU8sxR/logo-r1_d9d437c8.png"
            alt="TrueAxis HQ"
            className="h-8 w-auto object-contain"
          />
        </div>
      </nav>

      {/* Hero */}
      <section className="py-10 sm:py-14 px-4 text-center bg-gradient-to-b from-[#1A2E2A] to-[#0D1117]">
        <h1 className="text-4xl sm:text-5xl font-extrabold mb-4">Help Center</h1>
        <p className="text-[#3D3D3D] mb-8 max-w-lg mx-auto">Find answers to common questions, or contact our support team.</p>
        <div className="relative max-w-lg mx-auto">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500" />
          <input
            type="search"
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search for answers..."
            className="w-full pl-10 pr-4 py-3.5 bg-white border border-[#DDDBD7] rounded-xl text-[#1A1A1A] placeholder-[#9B9B9B] text-sm focus:outline-none focus:ring-2 focus:ring-[#D4922A] transition-colors"
          />
        </div>
      </section>

      {/* Category pills */}
      {!search && (
        <div className="px-4 py-4 flex flex-wrap gap-2 justify-center border-b border-[#DDDBD7]">
          <button
            onClick={() => setActiveCategory(null)}
            className={`px-4 py-2 rounded-full text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-[#D4922A] ${!activeCategory ? "bg-[#D4922A] text-white" : "bg-[#EEECEA] text-[#6B6B6B] hover:bg-[#E5E3DF]"}`}
          >
            All Topics
          </button>
          {categories.map(cat => (
            <button
              key={cat.title}
              onClick={() => setActiveCategory(activeCategory === cat.title ? null : cat.title)}
              className={`px-4 py-2 rounded-full text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-[#D4922A] ${activeCategory === cat.title ? "bg-[#D4922A] text-white" : "bg-[#EEECEA] text-[#6B6B6B] hover:bg-[#E5E3DF]"}`}
            >
              {cat.title}
            </button>
          ))}
        </div>
      )}

      {/* Articles */}
      <div className="max-w-3xl mx-auto px-4 py-8 space-y-10">
        {filtered
          .filter(cat => !activeCategory || cat.title === activeCategory)
          .map(cat => (
            <section key={cat.title}>
              <div className="flex items-center gap-3 mb-6">
                <div className="w-9 h-9 rounded-xl bg-[#D4922A]/15 flex items-center justify-center">
                  <cat.icon className="w-4 h-4 text-[#D4922A]" />
                </div>
                <h2 className="text-lg font-bold">{cat.title}</h2>
              </div>
              <div className="space-y-2">
                {cat.articles.map(a => <ArticleAccordion key={a.q} {...a} />)}
              </div>
            </section>
          ))}

        {filtered.length === 0 && (
          <div className="text-center py-16">
            <p className="text-gray-500 text-sm">No results found for "{search}". Try a different search term.</p>
          </div>
        )}

        {/* Contact support */}
        <section className="bg-white/5 border border-[#DDDBD7] rounded-xl p-8 text-center">
          <h2 className="text-xl font-bold mb-2">Still need help?</h2>
          <p className="text-[#6B6B6B] text-sm mb-6">Our support team typically responds within 4 business hours.</p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <a
              href="mailto:support@trueaxishq.com"
              className="flex items-center justify-center gap-2 bg-[#D4922A] hover:bg-[#D4911A] text-white px-6 py-3 rounded-xl text-sm font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-[#D4922A] focus:ring-offset-2 focus:ring-offset-[#F2F0EC] min-h-[48px]"
            >
              <Mail className="w-4 h-4" />
              Email Support
            </a>
            <button
              onClick={() => navigate("/dashboard")}
              className="flex items-center justify-center gap-2 bg-[#EEECEA] hover:bg-[#E5E3DF] text-[#1A1A1A] px-6 py-3 rounded-xl text-sm font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-[#D4922A] min-h-[48px]"
            >
              <ChevronRight className="w-4 h-4" />
              Open Dashboard
            </button>
          </div>
          <p className="text-xs text-gray-600 mt-4">support@trueaxishq.com · Mon–Fri, 9am–6pm CT</p>
        </section>
      </div>

      <footer className="border-t border-[#DDDBD7] py-8 px-4 text-center text-xs text-[#6B6B6B]">
        <p>© {new Date().getFullYear()} TrueAxis HQ. All rights reserved.</p>
      </footer>
    </div>
  );
}
