import { CheckCircle2, CircleAlert, ExternalLink, Mail, CalendarDays, CreditCard, Building2, Link2, Rocket, Loader2, ShieldCheck } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";

interface Props { onNavigate?: (panel: "settings" | "billing" | "scheduling" | "clients") => void; }

export default function LaunchReadiness({ onNavigate }: Props) {
  const { data, isLoading, refetch, isFetching } = trpc.settings.launchReadiness.useQuery();
  const { data: preflight, isLoading: preflightLoading } = trpc.settings.clientExperiencePreflight.useQuery();
  if (isLoading) return <div className="space-y-5"><div className="h-10 w-72 animate-pulse rounded-xl bg-slate-100" /><div className="grid gap-4 md:grid-cols-2">{Array.from({ length: 5 }).map((_, index) => <div key={index} className="h-36 animate-pulse rounded-2xl bg-slate-100" />)}</div></div>;
  if (!data) return <div className="rounded-2xl bg-rose-50 p-6 text-rose-800">Unable to load launch readiness. Refresh and try again.</div>;
  const steps = [
    { id: "business", label: "Business profile", detail: data.business.configured ? `${data.business.name ?? "Business"} profile is ready.` : "Add your business name and website so clients know who they are working with.", configured: data.business.configured, icon: Building2, action: "Open Settings", panel: "settings" as const },
    { id: "booking", label: "Booking page", detail: data.booking.configured ? `Your public booking link is ready at /book/${data.booking.username}.` : "Set your booking handle and at least one service before sharing a booking link.", configured: data.booking.configured, icon: CalendarDays, action: "Open Scheduling", panel: "scheduling" as const },
    { id: "portal", label: "Client Portal", detail: data.portal.configured ? "At least one secure client portal link is active." : "Create a client portal link when you want to share billing, milestones, photos, and messages.", configured: data.portal.configured, icon: Link2, action: "Open Clients", panel: "clients" as const },
    { id: "payments", label: "Payments", detail: data.payments.configured ? "Stripe credentials are present. Run a test checkout before charging customers." : "Connect a payment provider before inviting paying customers.", configured: data.payments.configured, icon: CreditCard, action: "Open Billing", panel: "billing" as const },
    { id: "email", label: "Transactional email", detail: data.email.configured ? `SMTP is configured${data.email.sender ? ` for ${data.email.sender}` : ""}${data.email.secure ? " with implicit TLS." : " with STARTTLS."}` : `SMTP is optional for testing, but required to send real booking, invoice, reset, and reminder emails.${data.email.issues?.length ? ` Missing or invalid: ${data.email.issues.join(", ")}.` : ""}`, configured: data.email.configured, icon: Mail, action: "See setup guide", panel: "settings" as const },
  ];
  const complete = steps.filter(step => step.configured).length;

  return <div className="mx-auto max-w-5xl space-y-6 pb-8">
    <header className="rounded-3xl bg-[#1C2333] p-6 text-white sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#f5c36d]">Launch control</p><h1 className="mt-2 text-3xl font-bold">Launch Readiness Center</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-white/70">Use this operational checklist to finish the essentials before sharing TrueAxis HQ with paying clients. It never exposes credentials or secret values.</p></div><div className="rounded-2xl bg-white/10 p-4 text-center"><p className="text-3xl font-bold">{complete}/{steps.length}</p><p className="mt-1 text-xs font-semibold uppercase tracking-wide text-white/60">Ready signals</p></div></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#D4922A] transition-all" style={{ width: `${complete / steps.length * 100}%` }} /></div></header>
    <section className="grid gap-4 md:grid-cols-2">{steps.map(step => <article key={step.id} className={`rounded-2xl border p-5 ${step.configured ? "border-emerald-100 bg-emerald-50/45" : "border-[rgba(26,26,26,0.1)] bg-white"}`}><div className="flex gap-4"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${step.configured ? "bg-emerald-100 text-emerald-700" : "bg-amber-50 text-[#D4922A]"}`}><step.icon className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><h2 className="font-bold text-[#1A1A1A]">{step.label}</h2>{step.configured ? <span className="inline-flex items-center gap-1 text-xs font-bold text-emerald-700"><CheckCircle2 className="h-4 w-4" /> Ready</span> : <span className="inline-flex items-center gap-1 text-xs font-bold text-amber-700"><CircleAlert className="h-4 w-4" /> Needs setup</span>}</div><p className="mt-2 text-sm leading-relaxed text-[rgba(26,26,26,0.62)]">{step.detail}</p><Button variant="outline" onClick={() => onNavigate?.(step.panel)} className="mt-4 h-9 border-[rgba(26,26,26,0.14)] text-[#1A1A1A]"><ExternalLink className="mr-1.5 h-3.5 w-3.5" />{step.action}</Button></div></div></article>)}</section>
    {preflightLoading ? <section className="h-64 animate-pulse rounded-2xl bg-slate-100" /> : preflight ? <section className="rounded-2xl border border-[#1C2333]/10 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#D4922A]">Client experience preflight</p><h2 className="mt-1 text-xl font-bold text-[#1A1A1A]">Review the journey before your client sees it</h2><p className="mt-1 max-w-2xl text-sm leading-relaxed text-[rgba(26,26,26,0.62)]">A private, read-only check of identity, booking, portal, payments, email, and automation readiness. It never opens client records or triggers an action.</p></div><div className={`inline-flex shrink-0 items-center gap-2 rounded-full px-3 py-1.5 text-xs font-bold ${preflight.overallState === "ready" ? "bg-emerald-50 text-emerald-700" : preflight.overallState === "attention" ? "bg-amber-50 text-amber-700" : "bg-rose-50 text-rose-700"}`}><ShieldCheck className="h-4 w-4" />{preflight.overallState === "ready" ? "Ready to share" : preflight.overallState === "attention" ? "Review recommended" : "Action required"}</div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{preflight.checks.map(check => <article key={check.id} className="rounded-xl border border-[rgba(26,26,26,0.08)] p-4"><div className="flex items-start gap-3"><div className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${check.state === "ready" ? "bg-emerald-50 text-emerald-700" : check.state === "attention" ? "bg-amber-50 text-amber-700" : "bg-rose-50 text-rose-700"}`}>{check.state === "ready" ? <CheckCircle2 className="h-4 w-4" /> : <CircleAlert className="h-4 w-4" />}</div><div className="min-w-0"><h3 className="text-sm font-bold text-[#1A1A1A]">{check.label}</h3><p className="mt-1 text-xs leading-relaxed text-[rgba(26,26,26,0.62)]">{check.detail}</p><p className="mt-2 text-xs font-semibold text-[#8a5a0b]">Next: {check.nextAction}</p></div></div></article>)}</div></section> : null}
    <section className="rounded-2xl border border-[#D4922A]/25 bg-[#fffaf0] p-5"><div className="flex gap-3"><Rocket className="mt-0.5 h-5 w-5 shrink-0 text-[#D4922A]" /><div><h2 className="font-bold text-[#1A1A1A]">Before you announce the product</h2><p className="mt-1 text-sm leading-relaxed text-[rgba(26,26,26,0.65)]">Complete a real booking, client-portal, invoice, payment, and password-reset journey with a test client. Configure SMTP before relying on automated email notifications, then refresh this checklist to confirm the sending setup.</p><Button variant="outline" onClick={() => void refetch()} disabled={isFetching} className="mt-4 border-[#D4922A]/35 text-[#8a5a0b]">{isFetching ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <CheckCircle2 className="mr-2 h-4 w-4" />} Refresh readiness</Button></div></div></section>
  </div>;
}
