import { useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { FeatureLock } from "@/components/FeatureLock";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { toast } from "sonner";
import { CheckCircle2, Clipboard, Code2, ExternalLink, Eye, EyeOff, Loader2, Plus, Power, Send, ShieldCheck, Trash2, TriangleAlert, Webhook } from "lucide-react";
import { WORKFLOW_WEBHOOK_EVENTS, type WorkflowWebhookEvent } from "@shared/workflowWebhooks";

const eventLabel: Record<WorkflowWebhookEvent, string> = {
  "app.booking.created": "New booking created",
  "app.client.created": "New client added",
  "app.invoice.paid": "Invoice paid",
  "app.proposal.signed": "Proposal signed",
  "job.status_changed": "Job status changed",
  "service_visit.scheduled": "Service visit scheduled",
  "service_visit.status_changed": "Service visit status changed",
};

const blankForm = () => ({ name: "", endpointUrl: "", events: [] as WorkflowWebhookEvent[] });

const webhookDataExamples: Record<WorkflowWebhookEvent, Record<string, unknown>> = {
  "app.booking.created": { bookingId: 1420, service: "Interior painting", date: "2026-09-24", preferredTime: "morning" },
  "app.client.created": { clientId: 311, name: "Jordan Reyes", email: null },
  "app.invoice.paid": { invoiceId: 8806, invoiceNumber: "INV-0087", amount: 1250 },
  "app.proposal.signed": { proposalId: 204, signatureName: "Jordan Reyes", total: 4312.5 },
  "job.status_changed": { jobId: 42, previousStatus: "approved", status: "in_progress" },
  "service_visit.scheduled": { visitId: 19, jobId: 42, teamMemberId: 7, title: "Onsite installation", scheduledStart: "2026-08-26T15:00:00.000Z", scheduledEnd: "2026-08-26T16:00:00.000Z" },
  "service_visit.status_changed": { visitId: 19, jobId: 42, previousStatus: "scheduled", status: "en_route" },
};

const eventEnvelope = (event: WorkflowWebhookEvent) => JSON.stringify({ id: "evt_example", type: event, occurredAt: "2026-08-26T15:00:00.000Z", data: webhookDataExamples[event] }, null, 2);

export default function WorkflowWebhooks() {
  const utils = trpc.useUtils();
  const { data: hooks = [], isLoading } = trpc.webhooks.list.useQuery();
  const { data: deliveries = [] } = trpc.webhooks.deliveries.useQuery();
  const [createOpen, setCreateOpen] = useState(false);
  const [form, setForm] = useState(blankForm);
  const [signingSecret, setSigningSecret] = useState<string | null>(null);
  const [showSecret, setShowSecret] = useState(false);

  const invalidate = () => { void utils.webhooks.list.invalidate(); void utils.webhooks.deliveries.invalidate(); };
  const create = trpc.webhooks.create.useMutation({
    onSuccess: result => { invalidate(); setCreateOpen(false); setForm(blankForm()); setSigningSecret(result.signingSecret); setShowSecret(true); toast.success("Webhook endpoint created. Save its signing secret now."); },
    onError: error => toast.error(error.message),
  });
  const update = trpc.webhooks.update.useMutation({ onSuccess: invalidate, onError: error => toast.error(error.message) });
  const remove = trpc.webhooks.remove.useMutation({ onSuccess: () => { invalidate(); toast.success("Webhook endpoint removed."); }, onError: error => toast.error(error.message) });
  const processDue = trpc.webhooks.processDue.useMutation({
    onSuccess: summary => { invalidate(); toast.success(`Recovery check completed: ${summary.delivered} delivered, ${summary.retryable} retryable, ${summary.terminal} terminal.`); },
    onError: error => toast.error(error.message),
  });

  const deliveryStats = useMemo(() => ({ delivered: deliveries.filter(delivery => delivery.status === "delivered").length, retryable: deliveries.filter(delivery => delivery.status === "retryable" || delivery.status === "pending").length, terminal: deliveries.filter(delivery => delivery.status === "failed" || delivery.status === "terminal").length }), [deliveries]);
  const submit = () => {
    if (!form.name.trim()) return toast.error("Name the endpoint.");
    if (!form.endpointUrl.trim()) return toast.error("Enter an HTTPS endpoint URL.");
    if (!form.events.length) return toast.error("Select at least one event.");
    create.mutate({ name: form.name.trim(), endpointUrl: form.endpointUrl.trim(), events: form.events });
  };
  const copySecret = async () => {
    if (!signingSecret) return;
    try { await navigator.clipboard.writeText(signingSecret); toast.success("Signing secret copied."); }
    catch { toast.error("Copy failed. Select and copy the secret manually."); }
  };

  if (isLoading) return <div className="h-[480px] rounded-2xl bg-slate-100 animate-pulse" />;
  return <FeatureLock feature="webhooks" label="Outbound webhooks"><div className="space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#D4922A]">Ecosystem</p><h1 className="mt-1 text-2xl font-bold text-[#1A1A1A]">Workflow Webhooks</h1><p className="mt-1 max-w-2xl text-sm text-[rgba(26,26,26,0.62)]">Send selected business events to an owner-approved HTTPS endpoint with a signed payload and durable delivery evidence.</p></div><Button onClick={() => setCreateOpen(true)} className="bg-[#D4922A] text-white hover:bg-[#B87716]"><Plus className="mr-2 h-4 w-4" /> Add endpoint</Button></header>

    <section className="rounded-2xl border border-[#D4922A]/25 bg-[#D4922A]/5 p-4"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 flex-shrink-0 text-[#9A610A]" /><div><h2 className="text-sm font-bold text-[#1A1A1A]">Signed, owner-controlled event bridge</h2><p className="mt-1 text-xs leading-5 text-[rgba(26,26,26,0.65)]">Endpoints must use public HTTPS. TrueAxis HQ rejects local/private destinations, limits the workspace to three endpoints, and records success or failure without rolling back the original job or dispatch action. This is not a marketplace certification or guaranteed third-party execution service.</p></div></div></section>

    <section className="grid gap-3 sm:grid-cols-4"><Metric label="Configured endpoints" value={String(hooks.length)} detail="Maximum three per workspace" /><Metric label="Delivered" value={String(deliveryStats.delivered)} detail="Most recent 100 deliveries" /><Metric label="Awaiting retry" value={String(deliveryStats.retryable)} detail="Retryable delivery attempts" /><Metric label="Needs review" value={String(deliveryStats.terminal)} detail="Terminal or historical failures" warn={deliveryStats.terminal > 0} /></section>

    <section className="rounded-2xl border border-[#1B2D4F]/15 bg-[#F8FBFB] p-5"><div className="flex items-start gap-3"><Code2 className="mt-0.5 h-5 w-5 shrink-0 text-[#007A68]" /><div><h2 className="font-bold text-[#1A1A1A]">Build a receiver with the exact event contract</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-[rgba(26,26,26,0.66)]">Your endpoint receives JSON via HTTPS. Preserve the raw request body, verify the HMAC before parsing it, and return a 2xx response only after your receiver accepts the event. Each delivery has a unique event ID for downstream idempotency.</p></div></div><div className="mt-4 grid gap-3 lg:grid-cols-2"><div className="rounded-xl border border-[#1B2D4F]/10 bg-white p-4"><p className="text-xs font-bold uppercase tracking-wide text-[#1B2D4F]">Required verification</p><div className="mt-3 space-y-2 text-xs text-[#3D3D3D]"><p><code className="rounded bg-[#F2F5F5] px-1.5 py-0.5">X-TrueAxis-Event</code> identifies the event type.</p><p><code className="rounded bg-[#F2F5F5] px-1.5 py-0.5">X-TrueAxis-Event-Id</code> is the idempotency key.</p><p><code className="rounded bg-[#F2F5F5] px-1.5 py-0.5">X-TrueAxis-Timestamp</code> is Unix seconds.</p><p><code className="rounded bg-[#F2F5F5] px-1.5 py-0.5">X-TrueAxis-Signature</code> is lowercase HMAC-SHA256.</p></div><pre className="mt-3 overflow-x-auto rounded-lg bg-[#1B2D4F] p-3 text-[11px] leading-5 text-white">{`expected = HMAC_SHA256(secret, timestamp + "." + rawRequestBody)\naccept only if timing-safe-equal(expected, X-TrueAxis-Signature)`}</pre></div><div className="rounded-xl border border-[#1B2D4F]/10 bg-white p-4"><p className="text-xs font-bold uppercase tracking-wide text-[#1B2D4F]">Delivery expectations</p><ul className="mt-3 space-y-2 text-xs leading-5 text-[#3D3D3D]"><li>Use the one-time signing secret shown when the endpoint is created; store it in your receiving system.</li><li>Return a 2xx status once the event is accepted. Non-2xx and network failures appear in delivery evidence.</li><li>TrueAxis HQ does not roll back a job or dispatch update when your endpoint fails.</li><li>Use event ID de-duplication in your receiver. Automatic retry scheduling is not included in this release.</li></ul></div></div><details className="mt-4 rounded-xl border border-[#1B2D4F]/10 bg-white p-4"><summary className="cursor-pointer text-sm font-bold text-[#1A1A1A]">View supported event payload examples</summary><div className="mt-4 grid gap-3 lg:grid-cols-3">{WORKFLOW_WEBHOOK_EVENTS.map(event => <div key={event} className="min-w-0"><p className="mb-2 text-xs font-semibold text-[#007A68]">{event}</p><pre className="overflow-x-auto rounded-lg bg-[#1B2D4F] p-3 text-[10px] leading-4 text-white">{eventEnvelope(event)}</pre></div>)}</div></details></section>

    <section className="rounded-2xl border border-[rgba(26,26,26,0.1)] bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold text-[#1A1A1A]">Endpoints</h2><p className="mt-1 text-xs text-[rgba(26,26,26,0.56)]">A signing secret is shown once at creation and stored encrypted on the server.</p></div><Webhook className="h-5 w-5 text-[#D4922A]" /></div>{hooks.length === 0 ? <div className="mt-5 rounded-xl bg-[#F7F6F3] px-5 py-10 text-center"><Code2 className="mx-auto h-8 w-8 text-[#D4922A]" /><h3 className="mt-3 text-sm font-bold text-[#1A1A1A]">No workflow endpoints yet</h3><p className="mx-auto mt-1 max-w-md text-xs text-[rgba(26,26,26,0.56)]">Add an endpoint when you have an authorized downstream workflow ready to verify TrueAxis HQ’s signed events.</p><Button size="sm" onClick={() => setCreateOpen(true)} className="mt-4 bg-[#1C2333] text-white hover:bg-[#2B3446]"><Plus className="mr-1 h-4 w-4" /> Add endpoint</Button></div> : <div className="mt-4 space-y-3">{hooks.map(hook => <article key={hook.id} className="rounded-xl border border-[rgba(26,26,26,0.1)] p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-bold text-[#1A1A1A]">{hook.name}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${hook.active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{hook.active ? "Active" : "Paused"}</span>{hook.failureCount > 0 && <span className="rounded-full bg-rose-50 px-2 py-0.5 text-[10px] font-bold text-rose-700">{hook.failureCount} recent failure{hook.failureCount === 1 ? "" : "s"}</span>}</div><p className="mt-1 break-all text-xs text-[rgba(26,26,26,0.58)]">{hook.endpointUrl}</p><div className="mt-3 flex flex-wrap gap-1.5">{hook.events.map(event => <span key={event} className="rounded-full bg-[#F7F6F3] px-2 py-1 text-[10px] font-semibold text-[rgba(26,26,26,0.68)]">{eventLabel[event]}</span>)}</div>{hook.lastError && <p className="mt-3 rounded-lg bg-rose-50 px-3 py-2 text-xs text-rose-800">Last delivery issue: {hook.lastError}</p>}</div><div className="flex shrink-0 gap-2"><Button size="sm" variant="outline" onClick={() => update.mutate({ id: hook.id, active: !hook.active })} disabled={update.isPending} className="border-[rgba(26,26,26,0.14)] text-[#1A1A1A]"><Power className="mr-1 h-3.5 w-3.5" /> {hook.active ? "Pause" : "Resume"}</Button><button type="button" onClick={() => remove.mutate({ id: hook.id })} disabled={remove.isPending} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50" aria-label={`Remove ${hook.name}`}><Trash2 className="h-4 w-4" /></button></div></div></article>)}</div>}</section>

    <section className="rounded-2xl border border-[rgba(26,26,26,0.1)] bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold text-[#1A1A1A]">Recent delivery evidence</h2><p className="mt-1 text-xs text-[rgba(26,26,26,0.56)]">The latest 100 event attempts, including failed downstream responses.</p></div><Send className="h-5 w-5 text-[#D4922A]" /></div>{deliveries.length === 0 ? <p className="mt-4 rounded-xl bg-[#F7F6F3] p-5 text-center text-sm text-[rgba(26,26,26,0.58)]">Delivery evidence appears after an enabled endpoint receives one of its selected events.</p> : <div className="mt-4 overflow-x-auto"><table className="min-w-[700px] w-full text-left text-sm"><thead className="border-b border-[rgba(26,26,26,0.1)] text-xs uppercase tracking-wide text-[rgba(26,26,26,0.48)]"><tr><th className="px-2 py-3">Event</th><th className="px-2 py-3">Endpoint</th><th className="px-2 py-3">Status</th><th className="px-2 py-3">Outcome</th><th className="px-2 py-3">When</th></tr></thead><tbody>{deliveries.map(delivery => <tr key={delivery.id} className="border-b border-[rgba(26,26,26,0.06)] last:border-0"><td className="px-2 py-3 font-semibold text-[#1A1A1A]">{eventLabel[delivery.eventType]}</td><td className="px-2 py-3 text-[rgba(26,26,26,0.68)]">{delivery.webhookName}</td><td className="px-2 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${delivery.status === "delivered" ? "bg-emerald-50 text-emerald-700" : delivery.status === "failed" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-800"}`}>{delivery.status}</span></td><td className="max-w-[280px] truncate px-2 py-3 text-xs text-[rgba(26,26,26,0.6)]">{delivery.errorMessage || (delivery.responseStatus ? `HTTP ${delivery.responseStatus}` : "Awaiting outcome")}</td><td className="px-2 py-3 text-xs text-[rgba(26,26,26,0.56)]">{new Date(delivery.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>}</section>

    <section className="flex flex-col gap-3 rounded-2xl border border-[#D4922A]/20 bg-[#D4922A]/5 p-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs leading-5 text-[rgba(26,26,26,0.66)]">Retryable deliveries keep an encrypted, bounded event envelope until completion or terminal failure. You can process due work now; managed periodic retry scheduling remains a separate validation gate.</p><Button size="sm" variant="outline" onClick={() => processDue.mutate({ limit: 10 })} disabled={processDue.isPending} className="shrink-0 border-[#D4922A]/40 text-[#8A5400]"><Send className="mr-1.5 h-3.5 w-3.5" />{processDue.isPending ? "Processing…" : "Process due deliveries"}</Button></section>

    <Dialog open={createOpen} onOpenChange={open => { setCreateOpen(open); if (!open) setForm(blankForm()); }}><DialogContent className="max-w-xl bg-white"><DialogHeader><DialogTitle className="text-[#1A1A1A]">Add workflow endpoint</DialogTitle></DialogHeader><div className="space-y-4 py-2"><Field label="Endpoint name" value={form.name} onChange={value => setForm(current => ({ ...current, name: value }))} placeholder="e.g. Operations automation" /><Field label="Public HTTPS endpoint" value={form.endpointUrl} onChange={value => setForm(current => ({ ...current, endpointUrl: value }))} placeholder="https://automation.example.com/hooks/trueaxis" /><fieldset><legend className="text-sm font-semibold text-[#1A1A1A]">Events to send</legend><div className="mt-2 space-y-2">{WORKFLOW_WEBHOOK_EVENTS.map(event => <label key={event} className="flex items-start gap-2 rounded-lg border border-[rgba(26,26,26,0.1)] p-3 text-sm text-[#1A1A1A]"><input type="checkbox" checked={form.events.includes(event)} onChange={checked => setForm(current => ({ ...current, events: checked.target.checked ? [...current.events, event] : current.events.filter(item => item !== event) }))} className="mt-0.5 h-4 w-4 accent-[#D4922A]" /><span><strong>{eventLabel[event]}</strong><span className="mt-0.5 block text-xs text-[rgba(26,26,26,0.56)]">{event}</span></span></label>)}</div></fieldset><p className="flex gap-2 rounded-lg bg-[#F7F6F3] p-3 text-xs text-[rgba(26,26,26,0.62)]"><TriangleAlert className="h-4 w-4 flex-shrink-0 text-[#D4922A]" />Endpoint calls are signed and documented in the delivery log. A failed downstream request will not undo the TrueAxis HQ action that created the event.</p></div><DialogFooter><Button variant="outline" onClick={() => setCreateOpen(false)}>Cancel</Button><Button onClick={submit} disabled={create.isPending} className="bg-[#D4922A] text-white hover:bg-[#B87716]">{create.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : "Create endpoint"}</Button></DialogFooter></DialogContent></Dialog>

    <Dialog open={showSecret} onOpenChange={setShowSecret}><DialogContent className="max-w-xl bg-white"><DialogHeader><DialogTitle className="flex items-center gap-2 text-[#1A1A1A]"><ShieldCheck className="h-5 w-5 text-[#D4922A]" /> Save your signing secret</DialogTitle></DialogHeader><p className="text-sm text-[rgba(26,26,26,0.64)]">Copy this secret into your receiving system now. It is intentionally shown only once and is stored encrypted by TrueAxis HQ.</p><div className="mt-2 flex gap-2 rounded-lg bg-[#1C2333] p-3"><code className="min-w-0 flex-1 break-all text-xs text-white">{signingSecret}</code><Button size="sm" type="button" onClick={copySecret} className="shrink-0 bg-[#D4922A] text-white hover:bg-[#B87716]"><Clipboard className="mr-1 h-3.5 w-3.5" /> Copy</Button></div><DialogFooter><Button onClick={() => { setShowSecret(false); setSigningSecret(null); }} className="bg-[#1C2333] text-white hover:bg-[#2B3446]"><CheckCircle2 className="mr-1 h-4 w-4" /> I saved it</Button></DialogFooter></DialogContent></Dialog>
  </div></FeatureLock>;
}

function Metric({ label, value, detail, warn = false }: { label: string; value: string; detail: string; warn?: boolean }) { return <div className="rounded-2xl border border-[rgba(26,26,26,0.1)] bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-[rgba(26,26,26,0.48)]">{label}</p><p className={`mt-2 text-2xl font-bold ${warn ? "text-rose-600" : "text-[#1A1A1A]"}`}>{value}</p><p className="mt-1 text-xs text-[rgba(26,26,26,0.56)]">{detail}</p></div>; }
function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) { return <label className="block text-sm font-semibold text-[#1A1A1A]">{label}<input value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="mt-1.5 block w-full rounded-lg border border-[rgba(26,26,26,0.16)] bg-white px-3 py-2 text-sm font-normal text-[#1A1A1A] outline-none focus:ring-2 focus:ring-[#D4922A]/35" /></label>; }
